### ISSUE TITLE
Question/Feature request: Overwrite change callback if they have the same name or allow cleaning callback list

### ISSUE THREAD

**Issue by FelipeCybis** [Kitware/trame-server#19]
Hello!

I saw that in v2.13 (more specifically 61de095dac00ba02fd5b1cbd94d694c82ee022f8) the internal attribute `_change_callback`  was moved from `Server`  to `State` (and others). So I plead guilty on using an internal attribute, but here is why I was using it:

I use PyVista for creating my scene and then I have a variable "play" for example that will have an associated callback function (`server.change("play")(function)`) the problem is that the `change` decorator **appends** the new function to a callback list for the `"play"` variable.
So if I have my scene created in a jupyter cell, and I re-run this cell, I will have copies of the same callback function being called when `"play"` changes.

Is there a correct way to clean the callback functions associated to a variable? What is the intended steps to make so that the function is not copied multiple times to the callback list when re-running the jupyter cell? I could not find any besides using the internal `_change_callbacks["play"] = [callback_function]`

If there isn't any, that would be my feature request: cleaning the callback list for a specific variable.

**Comment by jourdain** [comment]
Hi @FelipeCybis, it is nice to see "advanced" usage of trame. 

And I guess if you don't mind, let's try to find a path together that is more viable long-term for everyone. 

__Question:__ Is that truly the same function or an actual new one since that function is also defined within that cell?
=>  if it was the same, we could use a set instead of a list.

Another option could be to use the controller indirection and central model like the one below.

```python
state, ctrl = server.state, server.controller
state.change("play")(ctrl.on_play_changed)
```

```python
ctrl.on_play_changed = fn
```

**Comment by jourdain** [comment]
The possible path forward:
- use a set instead of a list (might still be not enough)
- add public API to clear, remove or unsubscribe registered functions/methods. 

If you have any suggestions of pseudo-code, feel free to share your thoughts.

Possible idea below

```python 
unregister = state.listeners.add(fn, "name_a", "name_b")

# ...
unregister()

state.listeners.clear("name_a")
state.listeners.clear() # clear all
state.listeners.remove(fn) # remove given fn on any change listener
```

**Comment by FelipeCybis** [comment]
Hey again @jourdain :)

> Question: Is that truly the same function or an actual new one since that function is also defined within that cell?
=> if it was the same, we could use a set instead of a list.

Hmm, good question! It is indeed a new one since I wrap all this into a class and the class is instanciated every run.
If I use the controller function as you suggested, it appends the exact same function. (sorry for the blurring of the function names, the code does not belong to me). Here I used the controller method for `"play"` and just adding a class method for `"step"` through `self.server.change("step")(self.fn)`.
![image](https://github.com/Kitware/trame-server/assets/41338087/e28addae-4036-482e-9a6e-f152a5c76604)

I guess then that if using the controller method, using set would be enough, but I suppose forcing this is not viable for `trame`?

I was thinking in something kind of similar to `StateChangeHandler`, but for the purpose of handling what exactly is in `state._change_callbacks` which is more or less what you proposed.

A simpler solution could possibly be adding `__delattr__` and `__delitem__` using the same magic you use in `__getattr__/__getitem__` and `__setattr__/__setitem__`. So `del state[key]` or `delattr(state, key)` would be enough.

```python
def __delitem__(self, key):
    key = self._translator.translate_key(key)
    if key in self._pushed_state:
        del self._pushed_state[key]
        return
        
    del self._pending_update[key]

def __delattr__(self, key):
    if is_dunder(key):
        return delattr(object, key)
     if is_private(key):
        del self.__dict__[key]
         return

    del self[key]
```

**Comment by jourdain** [comment]
If you are okay with using the controller as a middleman, that will alleviate any code change on the trame side. 

At that point, it depends on how your code gets used in the context of Jupyter. A better way would be to have a proper "unregister" when the object gets deleted, or a method is called on it. This could be an add-on of the `@trame.decorators.TrameApp()` where we could build some closure that the user can call to free the resources. If we go that way, it does not add more API per se, but you get a new method that you can call on the decorated instance to clear its registered state_change/controller_methods.

What do you think?

Moreover, I'm not sure I understand what you mean by:
> I guess then that if using the controller method, using set would be enough, but I suppose forcing this is not viable for trame?

**Comment by FelipeCybis** [comment]
> Moreover, I'm not sure I understand what you mean by:
>> I guess then that if using the controller method, using set would be enough, but I suppose forcing this is not viable for trame?

That was my fault, I did not have all the process in my mind, now I see there already is a `set` when the callbacks are called within `StateChangeHandler`. Forget what I said.

I will use the controller as middleman, no problem with that. I think this is the best solution here... there is no reason to enter a possible garbage collector rabbit hole and just add one thing for the user to have in mind when coding an App.

By using the controller as middleman there will still be copies of the same function in the `_change_callbacks` dictionary when code is re-run and the server is already on, though. I don't thing there is a problem per se here, but good to have in mind.

I will close this as my problem is solved. Thanks @jourdain!
