### ISSUE TITLE
Bug: reloading domain in trame-simput does not work with newest trame-server 

### ISSUE THREAD

**Issue by DavidBerger98** [Kitware/trame-server#4]
With the current version of `trame-server` updating the id of SimputItems does not work anymore.

If you run the [Widgets](https://github.com/Kitware/trame-simput/blob/master/examples/01_Widgets/app.py) example and change the active id with the drop-down in the upper right, it doesn't update anymore, but it works with `trame-server==2.2.0`.

**Comment by DavidBerger98** [comment]
I updated to trame-client 2.3.0 but the Widgets example still doesn't seem to work. Here are my trame versions:

```
trame==2.2.1
trame-client==2.3.0
trame-components==2.0.1
trame-deckgl==2.0.1
trame-markdown==2.0.2
trame-matplotlib==2.0.1
trame-plotly==2.0.1
trame-rca==0.2.1
trame-router==2.0.1
trame-server==2.4.1
trame-simput==2.2.1
trame-vega==2.0.2
trame-vtk==2.0.4
trame-vuetify==2.0.1
```

**Comment by jourdain** [comment]
So the issue was that the browser was caching the old trame-client code base. 

TLTR:  `trame-server>=2.2.0` needs `trame-client>=2.2.2` + cleared browser cache
