### ISSUE TITLE
@asyncio.coroutine removal as of python 3.11

### ISSUE THREAD

**Issue by cardinalgeo** [Kitware/trame-server#7]
**Describe the bug**

When running the "RemoteSelection" example [here](https://github.com/Kitware/trame/blob/master/examples/06_vtk/Applications/RemoteSelection/app.py) in the `trame` repo, I receive the following error: 

![image](https://user-images.githubusercontent.com/44422832/206871331-eea17846-1518-4ffa-b554-2ae3e4443990.png)

According to [here](https://docs.python.org/3.10/library/asyncio-task.html#asyncio.coroutine) in the `asyncio` documentation, as of `python 3.11` (Oct. 24th, 2022), `@asyncio.coroutine` has been removed and `async def` should be used instead. Expectedly, reverting to `python 3.10` resolves this issue. 

While I looked into making a pull request myself, I have no experience with `asyncio`, let alone the general asynchronous programming model. 

**To Reproduce**

1. `python examples/06_vtk/Applications/RemoteSelection/app.py`
2. See error

**Expected behavior**

As shown in the `trame` promotional video [here](https://kitware.github.io/trame/index.html) (00:51), we expect cross-selection of points between the vtk scene and the plotly scatter plot, where selection of points on one results in highlight in the other. However, this cross-selection capability is not present. Otherwise, the dashboard appears functional. 

**Platform:**

***Trame:***

- [ ] Version 1.x
- [x] Version 2.x

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [x] MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [x] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

**Comment by jourdain** [comment]
Thanks for pointing that out.

**Comment by cardinalgeo** [comment]
No problem!
